#!/usr/bin/env lua

local lfs = require("lfs")
local dotFileDir = ("$HOME/dotfiles/"):gsub("%$([a-zA-Z_]+)", os.getenv)
local locations = "locations.txt"

local fd = io.open(dotFileDir .. locations, "r")
if not fd then
	io.stderr:write("Unable to open " .. locations)
	os.exit(1)
end
local files = fd:read("a")
fd:close()

local pat = "(%S+)%s+%-%>%s+(%S+)"
for file, destDir in files:gmatch(pat) do
	destDir = destDir:gsub("%$([a-zA-Z_]+)", os.getenv)
	os.execute("rm -rf " .. destDir .. file)
	print(("linking %s to %s"):format(dotFileDir .. file, destDir .. file))
	local ok, res = lfs.link(dotFileDir .. file, destDir .. file, true)
	if not ok then
		print("\tCould not link:", res)
	end
end
